version: "3"
services:
   app:
      build:
         context: ./
         dockerfile: Dockerfile
      ports: 
      - "8080:8080"
   pg:
      image: postgres:11-alpine
      ports:
      - "5432:5432"
      environment:
      - "POSTGRES_PASSWORD=dalong"
